//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_DataAccessLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetail
    {
        public ProductDetail()
        {
            this.Inventory = new HashSet<Inventory>();
            this.InvoiceDetail = new HashSet<InvoiceDetail>();
        }
    
        public string ProductId { get; set; }
        public string ColorId { get; set; }
        public string SizeId { get; set; }
        public string BrandId { get; set; }
        public string MaterialId { get; set; }
        public double UnitPrice { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Color Color { get; set; }
        public virtual ICollection<Inventory> Inventory { get; set; }
        public virtual ICollection<InvoiceDetail> InvoiceDetail { get; set; }
        public virtual Material Material { get; set; }
        public virtual Product Product { get; set; }
        public virtual Size Size { get; set; }
    }
}
