//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_DataAccessLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles
    {
        public Roles()
        {
            this.Employee = new HashSet<Employee>();
            this.Shipper = new HashSet<Shipper>();
        }
    
        public string RoleId { get; set; }
        public string RoleName { get; set; }
    
        public virtual ICollection<Employee> Employee { get; set; }
        public virtual ICollection<Shipper> Shipper { get; set; }
    }
}
